CREATE DATABASE BDTODO;
USE BDTODO;
CREATE TABLE TAREA(
 ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 TITULO VARCHAR(400),
 NOTAS VARCHAR(500),
 ESTADO INT,
 PRIORIDAD INT,
 FECHA_CREACION DATETIME,
 FECHA_TERMINO DATETIME
);



--INSERT INTO TAREA(TITULO,NOTAS,ESTADO,PRIORIDAD,FECHA_CREACION,FECHA_TERMINO) 
--VALUES('TAREA','ESTA TAREA DE PRUEBA 4',1,'','');


--Creacion de los procedimientos almacenados
CREATE PROCEDURE sp_consultar_tareas
AS
	SET NOCOUNT ON;
	select ID,TITULO,NOTAS,ESTADO,PRIORIDAD,FECHA_CREACION,FECHA_TERMINO FROM TAREA;
GO

--EXEC sp_consultar_tareas;



CREATE PROCEDURE sp_buscarID   
    @ID int  
AS   
    SET NOCOUNT ON;  
	select ID,TITULO,NOTAS,ESTADO,PRIORIDAD,FECHA_CREACION,FECHA_TERMINO FROM TAREA 
    WHERE ID = @ID;  
GO  

CREATE PROCEDURE sp_buscarPrioridad   
    @PRIORIDAD int  
AS   
    SET NOCOUNT ON;  
	select ID,TITULO,NOTAS,ESTADO,PRIORIDAD,FECHA_CREACION,FECHA_TERMINO FROM TAREA 
    WHERE PRIORIDAD = @PRIORIDAD;  
GO  

--EXECUTE sp_buscarID @ID=1;
--EXECUTE sp_buscarPrioridad  @PRIORIDAD=2;

CREATE PROCEDURE sp_crear_tarea
	   @TITULO varchar(100),
	   @NOTAS varchar(400),
	   @ESTADO	INT,
	   @PRIORIDAD INT,
	   @FECHA_CREACION DATETIME,
	   @FECHA_TERMINO DATETIME
AS
BEGIN
INSERT INTO TAREA  (
	   TITULO,
	   NOTAS,
	   ESTADO,
	   PRIORIDAD,
	   FECHA_CREACION,
	   FECHA_TERMINO)
    VALUES (
	   @TITULO,
	   @NOTAS,
	   @ESTADO,
	   @PRIORIDAD,
	   @FECHA_CREACION,
	   @FECHA_TERMINO);
END
GO

--EXECUTE sp_crear_tarea 
--@TITULO='TAREA DESDE SP', @NOTAS='SOY UNA TAREITA',
--@ESTADO=1,@PRIORIDAD=3,@FECHA_CREACION='',
--@FECHA_TERMINO='';




CREATE PROC sp_actualizar_tarea
	@ID int,
	@TITULO varchar(100),
	@NOTAS varchar(400),
	@ESTADO	INT,
	@PRIORIDAD INT,
	@FECHA_CREACION DATETIME,
	@FECHA_TERMINO DATETIME
  
AS 
BEGIN 
UPDATE TAREA
SET  TITULO = @TITULO,
     NOTAS = @NOTAS, 
     ESTADO = @ESTADO,
     PRIORIDAD = @PRIORIDAD,
	 FECHA_CREACION =@FECHA_CREACION,
	 FECHA_TERMINO = @FECHA_TERMINO
WHERE  ID = @ID
END
GO
--EXECUTE sp_actualizar_tarea @ID=3,
--@TITULO='TAREA UPDATE DESDE SP', @NOTAS='SOY UPDATE UNA TAREITA',
--@ESTADO=1,@PRIORIDAD=3,@FECHA_CREACION='',
--@FECHA_TERMINO='';
--SELECT * FROM TAREA;

CREATE PROCEDURE sp_eliminar_tarea 
    @ID int
AS 
BEGIN 
DELETE
FROM   TAREA
WHERE  ID = @ID
END
GO
--EXECUTE sp_eliminar_tarea @ID=3;
SELECT * FROM TAREA;